# Generated by Django 4.2.1 on 2023-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='file',
            field=models.FileField(default=0, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
